### ISSUE TITLE
Unable to connect to my K8s Cluster w/ latest Arm MACOS version

### ISSUE THREAD

**Issue by tsteinholz** [kontena/lens#6492]
**Describe the bug**

After updating the following error message pops up on attempting to connect to an EKS cluster `E1031 20:32:13.743311 23106 proxy_server.go:147] Error while proxying request: getting credentials: exec: executable aws not found`. Also worth noting that the aws executable is in my path, but not sure why it would be using it to connect to my cluster.

**To Reproduce**
1. Update to latest version on Mac OSX

**Expected behavior**

Connect to the cluster

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: Lens: 2022.10.311317-latest
- OS: OSX 12.6 
- Installation method (e.g. snap or AppImage in Linux): Mac Install, in app update

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
E1031 20:32:13.743311 23106 proxy_server.go:147] Error while proxying request: getting credentials: exec: executable aws not found

It looks like you are trying to use a client-go credential plugin that is not installed.

To learn more about this feature, consult the documentation available at:
https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins

getting credentials: exec: executable aws not found

It looks like you are trying to use a client-go credential plugin that is not installed.

To learn more about this feature, consult the documentation available at:
https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.

I am able to connect fine via any other connection mechanism using my kube config.

**Additional context**
Same issue was reported here in #5676, however, this solution is not applicable to me as my aws executable is in my PATH.

```
# aws version
aws-cli/2.7.31 Python/3.10.8 Darwin/21.6.0 source/arm64 prompt/off
```

**Comment by kjwierenga** [comment]
I'm being held back by the same issue. Is there a way to downgrade Lens?

**Comment by kjwierenga** [comment]
> I'm being held back by the same issue. Is there a way to downgrade Lens?

Managed to fix this by changing `apiVersion` from `v1alpha1` to `v1beta1` in my kube config.

```yaml
users:
  - name: arn:aws:eks:eu-west-1:**account*number**:cluster/**my*cluster*name**
    user:
        exec:
            apiVersion: client.authentication.k8s.io/v1beta1 # was `v1alpha1
            args:
              - --region
              - eu-west-1
              - eks
              - get-token
              - --cluster-name
              - production
            command: aws
```

**Comment by cmorris98** [comment]
Also getting a similar but seeming related error after upgrading just now.  I am on an intel Mac.

Original error was.
"failed to initialize proxyexec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1""

After changing to v1beta1 as suggested above it still does not work for me and now gives me the error.

"Error while proxying request: getting credentials: decoding stdout: no kind "ExecCredential" is registered for version "client.authentication.k8s.io/v1alpha1" in scheme "pkg/runtime/scheme.go:100""

When I execute a kubectl get pods with v1beta1 I get the error 
"Unable to connect to the server: getting credentials: exec plugin is configured to use API version client.authentication.k8s.io/v1beta1, plugin returned version client.authentication.k8s.io/v1alpha1"

Any suggestions as to how I can fix this would be much appreciated as lens is totally down for me right now.

I am also trying to connect to EKS clusters. 

Any way I can downgrade to the previous version in order to get around this?

**Comment by matti** [comment]
Happens on Linux, Mac etc IF using EKS.

**Comment by kjwierenga** [comment]
Try upgrading awscli (to version 1.26.5) and kubectl (to version 1.25.3).

**Comment by julianhulsdouw** [comment]
> Try upgrading awscli (to version 1.26.5) and kubectl (to version 1.25.3).

Upgrading awscli was the fix for me, thanks 👍

**Comment by tsteinholz** [comment]
My kube config is already using the `apiVersion: client.authentication.k8s.io/v1beta1` but still produces this error.

It sounds like the latest version of lens requires a newer version of the AWS cli, which is not available on the homebrew package repos at this time.

I am already running the latest version of kubectl, that is also available via homebrew: `Client Version: v1.25.3`

For mac users, the[ latest aws cli version](https://formulae.brew.sh/formula/awscli) is only 1.26.0 at the moment 

<img width="659" alt="Screen Shot 2022-11-01 at 8 53 55 AM" src="https://user-images.githubusercontent.com/5491170/199236753-5329b3de-bf90-4e6f-9b06-441c998f0bcd.png">

Even downloading installing directly from the [AWS cli guide](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html), it still installs version 21.6.0 (no .5 available for mac?)

```
# aws --version
aws-cli/2.8.7 Python/3.9.11 Darwin/21.6.0 exe/x86_64 prompt/off
``` 

however, this is still generating the exact same error, even after an `aws eks update-config`

**Comment by cmorris98** [comment]
I was able to get this working. I am running v2 of the aws cli and updated to the latest 2.8.7. I then re-generated my config files with the command aws eks --region $region update-kubeconfig --name $cluster. After doing this lens was able to connect. And just for reference my kubectl version is 1.22.14 which isn't the latest, but it still works. Thanks for the help everyone..

**Comment by tsteinholz** [comment]
I have tried this as well as deleting the entire kubeconfig and regenerating it (with `aws eks update-kubeconfig`) but still getting `E1101 09:16:53.844597 19192 proxy_server.go:147] Error while proxying request: getting credentials: exec: executable aws not found`.

Original install location: `/opt/homebrew/bin/aws`
Updated install location: `/usr/local/bin/aws`

error persists on log out and reboot as well, so its not an issue with the PATH being out of date.

**Comment by c0state** [comment]
Opening Lens via the launcher icon doesn't pick up the path env var for some reason. Running `open /Applications/Lens.app/` in the terminal to launch works. I'm on Ventura but unsure if that's related.

**Comment by tsteinholz** [comment]
oh wow, this was my problem @c0state, thank you for that.

In conclusion, it seems like the latest version of Lens requires AWS CLI version v2.8.7, which is not available on homebrew (current version v2.7.31). Additionally, the Lens icon might be using stale PATH vars and requires to be updated in addition to manually re-installing the awscli.

I will leave this open for the project maintainers to decide if/how they would like to address this issue introduced in the latest version of the application.

**Comment by Nokel81** [comment]
We do actually try and pick up the shell env vars from your user configured SHELL. Sometimes this does fail though which is why running Lens from the command line fixes this issue.

There is no requirement about specific AWS CLI versions at all.

@c0state or @tsteinholz what shell are you using?

**Comment by c0state** [comment]
> We do actually try and pick up the shell env vars from your user configured SHELL. Sometimes this does fail though which is why running Lens from the command line fixes this issue.
> 
> There is no requirement about specific AWS CLI versions at all.
> 
> @c0state or @tsteinholz what shell are you using?

I'm running fish

**Comment by tsteinholz** [comment]
I am running fish as well.

**Comment by pqthang97** [comment]
I got a same problem.
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/14305217/199250942-11a73b82-d496-4505-8243-4d11f92caac1.png">

**Comment by tsteinholz** [comment]
@pqthang97 it sounded like the v1alpha1 auth isn't supported anymore, you can regenerate your eks config with the aws cli or try manually updating it to beta https://github.com/lensapp/lens/issues/6492#issuecomment-1298335413

**Comment by Nokel81** [comment]
Okay so it sounds like we are failing to load env vars within fish. I wonder if it is a similar problem to https://github.com/lensapp/lens/issues/6446 which was fixed by #6453

**Comment by jonnymccullagh** [comment]
Confirming this is a problem for me too. On Mac M1, using fish as my shell. Upgraded to `Lens: 2022.10.311317-latest` and getting the error: 
```
E1101 17:04:47.542752 8541 proxy_server.go:147] Error while proxying request: getting credentials: exec: executable aws not found
```
Tried updating aws cli to 2.8.7 and performed `update-kubeconfig`. kube-config already using v1beta1.
Developer tools showing path as: '/usr/bin:/bin:/usr/sbin:/sbin'

**Comment by ssadok** [comment]
I have the same problem but mon cluster is on 1.19 and this error showed up on kubectl version 1.26, so i tried to sete the kubectl app and i still have the same error

**Comment by tsteinholz** [comment]
@jonnymccullagh opening the app from the command line seems to be the (temporary) solution https://github.com/lensapp/lens/issues/6492#issuecomment-1298507101

**Comment by Nokel81** [comment]
We are investigating this issue regarding `fish` shell.

**Comment by williamnoble** [comment]
I tried the above solutions:
- bump apiVersion in kube config, already using `v1beta1`.
- awscli and kubectl already upto date.
- launching via terminal had no effect.

As a stop gap, i've changed my macOS shell back to zsh `chsh -s /bin/zsh` and this fixed the problem immediately.

**Comment by CumpsD** [comment]
Had this with the Windows version too, updating aws cli to the latest version fixed it.

**Comment by Nokel81** [comment]
FYI the fix to using `fish` has been posted as a PR

**Comment by share-me** [comment]
Same problem on Windows.
`"failed to initialize proxyexec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"`

to fix:
1. Update awscli to the last version
2. regenerate your eks config

**Comment by matti** [comment]
and for those using eksctl to generate config: manually change alpha to beta in the file.

**Comment by seaningham** [comment]
Downgrading to https://api.k8slens.dev/binaries/Lens-2022.10.181357-latest.dmg works in short term

**Comment by tsteinholz** [comment]
Hi @Nokel81,

I have just downloaded the latest Lens: 2022.11.41144-beta and am still experiencing this issue.

I can still open Lens in the terminal (using fish shell) and have it work, but just wanted to let you know incase the fix was expected to be included in this version.

Thanks,
Thomas

**Comment by Nokel81** [comment]
@tsteinholz That version does not yet include the fix.

**Comment by tsteinholz** [comment]
seems to be working in Lens: 2022.11.41434-beta now, thanks!

**Comment by Nokel81** [comment]
@tsteinholz Thanks for reporting back

**Comment by shivuslr41** [comment]
aws-cli upgrade to latest alone didn't help, upgrading aws-iam-authenticator to latest 0.5.9 helped solve this issue with v1beta1 changes as mentioned by https://github.com/lensapp/lens/issues/6492#issuecomment-1298335413

I'm on windows latest stable build lens app and using aws-cli & aws-iam-auth of wsl2.

**Comment by saiaptiv** [comment]
> I was able to get this working. I am running v2 of the aws cli and updated to the latest 2.8.7. I then re-generated my config files with the command aws eks --region $region update-kubeconfig --name $cluster. After doing this lens was able to connect. And just for reference my kubectl version is 1.22.14 which isn't the latest, but it still works. Thanks for the help everyone..

@cmorris98  Thank you so much for full details in one place . This helped me fix my issue.

**Comment by shearn89** [comment]
Just ran into this issue and this appeared via Google. Running `lens open` from the terminal solved the problem, although I'm surprised this isn't fixed 2 years after opening.
