### ISSUE TITLE
Lens polluting zsh history

### ISSUE THREAD

**Issue by boedy** [kontena/lens#6667]
**Describe the bug**
Lens is somehow polluting my zsh history. See some of the output of history (`~/.zsh_history`) file

**Logs:**
```
 9950  '/Applications/Lens.app/Contents/MacOS/Lens' -p '"68bd0de0064d4f8a9de919daf3019784" + JSON.stringify(process.env) + "68bd0de0064d4f8a9de919daf3019784"'
 9951  '/Applications/Lens.app/Contents/MacOS/Lens' -p '"7ccf665b9a014c9084c8afa9ea5e82ce" + JSON.stringify(process.env) + "7ccf665b9a014c9084c8afa9ea5e82ce"'
 9952  '/Applications/Lens.app/Contents/MacOS/Lens' -p '"49a19b8b90444cf68b3a110b27702350" + JSON.stringify(process.env) + "49a19b8b90444cf68b3a110b27702350"'
 9953  '/Applications/Lens.app/Contents/MacOS/Lens' -p '"982efec0705a4832a98f4049e70e0ebe" + JSON.stringify(process.env) + "982efec0705a4832a98f4049e70e0ebe"'
 9954  '/Applications/Lens.app/Contents/MacOS/Lens' -p '"7d7c085c48a348728b5c6ebea413007c" + JSON.stringify(process.env) + "7d7c085c48a348728b5c6ebea413007c"'
 9955  '/Applications/Lens.app/Contents/MacOS/Lens' -p '"872dc83df27149acb11280a1ccd3c416" + JSON.stringify(process.env) + "872dc83df27149acb11280a1ccd3c416"'
 9956  '/Applications/Lens.app/Contents/MacOS/Lens' -p '"c819f3d53ffb4c7d8fb9d8c923b775d3" + JSON.stringify(process.env) + "c819f3d53ffb4c7d8fb9d8c923b775d3"'
 9957  '/Applications/Lens.app/Contents/MacOS/Lens' -p '"5fcd0a7b99b7481b80be6482adcec116" + JSON.stringify(process.env) + "5fcd0a7b99b7481b80be6482adcec116"'
 9958  '/Applications/Lens.app/Contents/MacOS/Lens' -p '"418e4b221dde45389dee9a962f35e366" + JSON.stringify(process.env) + "418e4b221dde45389dee9a962f35e366"'
 9959  '/Applications/Lens.app/Contents/MacOS/Lens' -p '"d622d05699014d69a340b3d2a614bef6" + JSON.stringify(process.env) + "d622d05699014d69a340b3d2a614bef6"'
 9960  '/Applications/Lens.app/Contents/MacOS/Lens' -p '"864012c125d74d629e9e34be2c2dc111" + JSON.stringify(process.env) + "864012c125d74d629e9e34be2c2dc111"'
 9961  '/Applications/Lens.app/Contents/MacOS/Lens' -p '"eba4a28db2cd4ac8aaf061441503ee2c" + JSON.stringify(process.env) + "eba4a28db2cd4ac8aaf061441503ee2c"'
 9962  '/Applications/Lens.app/Contents/MacOS/Lens' -p '"c8c8b09f3fe7485b8dfb3750fdffc40b" + JSON.stringify(process.env) + "c8c8b09f3fe7485b8dfb3750fdffc40b"'
 9963  '/Applications/Lens.app/Contents/MacOS/Lens' -p '"010b52825dd34995a33755035faff27f" + JSON.stringify(process.env) + "010b52825dd34995a33755035faff27f"'
 9964  '/Applications/Lens.app/Contents/MacOS/Lens' -p '"956f7abe68ce4693b6514acac8bfef8b" + JSON.stringify(process.env) + "956f7abe68ce4693b6514acac8bfef8b"'
 9965  '/Applications/Lens.app/Contents/MacOS/Lens' -p '"79d01e0b24494c6f8f0a6c695a51d3a6" + JSON.stringify(process.env) + "79d01e0b24494c6f8f0a6c695a51d3a6"'
 9966  '/Applications/Lens.app/Contents/MacOS/Lens' -p '"095bf59a3e4e495490a4a234c0ff232a" + JSON.stringify(process.env) + "095bf59a3e4e495490a4a234c0ff232a"'
 9967  '/Applications/Lens.app/Contents/MacOS/Lens' -p '"7ce70b7d3c86436c8e4c759117e4243f" + JSON.stringify(process.env) + "7ce70b7d3c86436c8e4c759117e4243f"'
 9968  '/Applications/Lens.app/Contents/MacOS/Lens' -p '"487a6b4dfd7e44fa81d56864fcebe5e8" + JSON.stringify(process.env) + "487a6b4dfd7e44fa81d56864fcebe5e8"'
 9969  '/Applications/Lens.app/Contents/MacOS/Lens' -p '"9dd36678bd67472c8f25c0a664c2a2ca" + JSON.stringify(process.env) + "9dd36678bd67472c8f25c0a664c2a2ca"'
 9970  '/Applications/Lens.app/Contents/MacOS/Lens' -p '"50eb647d560e4de3b58b74af83723f0b" + JSON.stringify(process.env) + "50eb647d560e4de3b58b74af83723f0b"'
 9971  '/Applications/Lens.app/Contents/MacOS/Lens' -p '"0bb93afaf6184d79a594aa7478269940" + JSON.stringify(process.env) + "0bb93afaf6184d79a594aa7478269940"'
 9972  '/Applications/Lens.app/Contents/MacOS/Lens' -p '"155f4ff5392641f09174811c3c79062b" + JSON.stringify(process.env) + "155f4ff5392641f09174811c3c79062b"'
 9973  '/Applications/Lens.app/Contents/MacOS/Lens' -p '"228332a7767847949ccdcc296c21173d" + JSON.stringify(process.env) + "228332a7767847949ccdcc296c21173d"'
 9974  '/Applications/Lens.app/Contents/MacOS/Lens' -p '"64dbef5b5a0b4b4c97ae5e2548077ee0" + JSON.stringify(process.env) + "64dbef5b5a0b4b4c97ae5e2548077ee0"'
 9975  '/Applications/Lens.app/Contents/MacOS/Lens' -p '"2ebcc30cf222455bbf62ab038b24319a" + JSON.stringify(process.env) + "2ebcc30cf222455bbf62ab038b24319a"'
 9976  '/Applications/Lens.app/Contents/MacOS/Lens' -p '"5549f872bd634c2e9dcaae454af00dff" + JSON.stringify(process.env) + "5549f872bd634c2e9dcaae454af00dff"'
 9977  '/Applications/Lens.app/Contents/MacOS/Lens' -p '"98ce520c23b3490a812b83f5faf0acba" + JSON.stringify(process.env) + "98ce520c23b3490a812b83f5faf0acba"'
 ```

**Environment (please complete the following information):**
Lens: 2022.11.251411-latest
Extension API: 6.2.3
Electron: 19.1.7
Chrome: 102.0.5005.167
Node: 16.14.2
MacOS: 13.0 (22A380) (Ventura)

**Comment by Nokel81** [comment]
fixed by #6668

**Comment by PeterSzegedi** [comment]
Here, because this thing was triggering my paranoia.

**Comment by boedy** [comment]
This issues is still not fixed for me. Currently version information:

Lens: 2023.3.100736-latest
Extension API: 6.4.6
Electron: 19.1.9
Chrome: 102.0.5005.167
Node: 16.14.2

```
: 1676484499:0;'/Applications/Lens.app/Contents/MacOS/Lens' -p '"378ee9f3ecfa4a5a94c3792b90358841" + JSON.stringify(process.env) + "378ee9f3ecfa4a5a94c3792b90358841"'
: 1676484499:0;'/Applications/Lens.app/Contents/MacOS/Lens' -p '"1b2e67b784b74cd9b6dadaa040f6e66b" + JSON.stringify(process.env) + "1b2e67b784b74cd9b6dadaa040f6e66b"'
: 1676484501:0;'/Applications/Lens.app/Contents/MacOS/Lens' -p '"8869f662ec024d93ace79e5d65ce6f8b" + JSON.stringify(process.env) + "8869f662ec024d93ace79e5d65ce6f8b"'
: 1676484607:0;'/Applications/Lens.app/Contents/MacOS/Lens' -p '"35632cf0fee64631a996fe6ad50cfd75" + JSON.stringify(process.env) + "35632cf0fee64631a996fe6ad50cfd75"'
: 1676484607:1;'/Applications/Lens.app/Contents/MacOS/Lens' -p '"fe722632afb946bb8cf82877d2089e35" + JSON.stringify(process.env) + "fe722632afb946bb8cf82877d2089e35"'
: 1676495987:0;'/Applications/Lens.app/Contents/MacOS/Lens' -p '"b3ebdf4efbc245f9b37e41afa786187b" + JSON.stringify(process.env) + "b3ebdf4efbc245f9b37e41afa786187b"'
: 1676498125:0;'/Applications/Lens.app/Contents/MacOS/Lens' -p '"f1ac7d4e446240a2bfa1a1ed07a5eb50" + JSON.stringify(process.env) + "f1ac7d4e446240a2bfa1a1ed07a5eb50"'
: 1676498129:0;'/Applications/Lens.app/Contents/MacOS/Lens' -p '"f47b0deab02f4c6ea2a24a1cc54dfe52" + JSON.stringify(process.env) + "f47b0deab02f4c6ea2a24a1cc54dfe52"'
: 1676498130:0;'/Applications/Lens.app/Contents/MacOS/Lens' -p '"6e051cc8b7cf4d689ad733b87dab49cc" + JSON.stringify(process.env) + "6e051cc8b7cf4d689ad733b87dab49cc"'
: 1676541341:0;'/Applications/Lens.app/Contents/MacOS/Lens' -p '"147e8faa81e1440f976f1641b02e15ea" + JSON.stringify(process.env) + "147e8faa81e1440f976f1641b02e15ea"'
: 1676541344:0;'/Applications/Lens.app/Contents/MacOS/Lens' -p '"10db8ef7820b460387e1c124f6725dfb" + JSON.stringify(process.env) + "10db8ef7820b460387e1c124f6725dfb"'
: 1676541344:0;'/Applications/Lens.app/Contents/MacOS/Lens' -p '"f369e96461134bcb9e5bc251523a6cd0" + JSON.stringify(process.env) + "f369e96461134bcb9e5bc251523a6cd0"'

**Comment by Nokel81** [comment]
@boedy interesting... we are still prefixing with a ` ` in `packages/core/src/features/shell-sync/main/compute-unix-shell-environment.injectable.ts:87` and we just pass the value directly to the stdin of the shell process on line 179

**Comment by gabrielcho** [comment]
Can confirm, Lens is polluting my zsh command history:

'/Applications/Lens.app/Contents/MacOS/Lens' -p '"xxxxxxxxxxxxxxxxxxxxxxxxxx" + JSON.stringify(process.env) + "xxxxxxxxxxxxxxxxxxxxxxxxxx"'


Lens: 2024.11.261604-latest
Electron: 31.7.5
Chrome: 126.0.6478.234
Node: 20.18.0
© 2024 Mirantis, Inc
